### PR TITLE
Fix Travis Build

### PR DESCRIPTION
**Pull request by sysarcher**
Hello @jren1 

I think this should fix the issue you highlighted here: https://github.com/projectacrn/acrn-hypervisor/issues/145#issuecomment-392447256

### CODE REVIEW

**Comment by sysarcher** [comment]
I think Travis isn't wrong here:

```bash
gcc -c -Wall -Wextra -pedantic -m64 -D_GNU_SOURCE -DDEBUG_ACRN_CRASHLOG -I /root/acrn/tools/acrn-crashlog/common/include log_sys.c -o /root/acrn/build/tools/acrn-crashlog/common/obj/log_sys.o
log_sys.c:8:32: fatal error: systemd/sd-journal.h: No such file or directory
```

Its not compiling on my system either. But the CI seems to be set up correctly. Build failure is consistent with what I observe on my machine. 

[Build Status](https://travis-ci.org/jren1/acrn-hypervisor)

**Comment by gvancuts** [comment]
Hi @shrmrf , you're missing build dependencies in your Dockerfiles. I'm still (somewhat) maintaining a set of Dockerfiles in my own repo [here](https://github.com/gvancuts/acrn-dockerfiles). We should update the Dockerfiles to these versions. We will still hit some compilation issues on *some* distributions but at least Ubuntu 16.04 and Clearlinux should pass.

**Comment by gvancuts** [comment]
@shrmrf @jren1 take a look at this one: https://github.com/gvancuts/acrn-hypervisor/pull/5 (Travis CI config update is in this patch: https://github.com/gvancuts/acrn-hypervisor/commit/af2f3ed3dcdf2e2518d8788d3f611eea3c6422df)

**Comment by sysarcher** [comment]
@gvancuts yeah, your PR looks better. Closing this one here.

**Pull request closed without merging**
